"project_id" : "3"
"base_path" : "."
"api_token_env" : "CROWDIN_PERSONAL_TOKEN"
"base_url" : "https://teamgalacticraft.crowdin.com"
"commit_message" : "[ci skip] fix: sync new translations for %language% from Crowdin"
"append_commit_message" : false
"preserve_hierarchy" : false
files: [
 {
  "source" : "/src/main/resources/assets/galacticraft/lang/en_US.json",
  "translation" : "/src/main/resources/assets/galacticraft/lang/%locale_with_underscore%.json",
  "type" : "json",
 }
]
